### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by wally-wally** [wally-wally/drf-api-sandbox#1]
- [x] `django` 프로젝트 세팅
- [x] 할 일 목록 가져오는 로직 구현(R)
- [x] 할 일 목록 조회 API에 할 일 개수 항목 추가(R)
- [x] 할 일 상세 내용 가져오는 로직 구현(R)
- [x] 할 일 추가 로직 구현(C)
- [x] 할 일 삭제 로직 구현(D)
- [x] 할 일 수정 로직 구현(U)
- [x] 할 일 완료 여부 변경 로직 구현(U)
- [x] `swagger` 문서 작성
- [ ] `FBV` 방식에서 `CBV` 방식으로 전환 ([FBV vs CBV 비교 참고 문서](https://dingrr.com/blog/post/djangofbvs-vs-cbvs-%ED%95%A8%EC%88%98%ED%98%95-%EB%B7%B0-vs-%ED%81%B4%EB%9E%98%EC%8A%A4%ED%98%95-%EB%B7%B0))
